### ISSUE TITLE
Spring Boot 2.0 apps cannot be launched with Spring Boot 1.x

### ISSUE THREAD

**Issue by dsyer** [dsyer/spring-boot-thin-launcher#47]
Not really very surprising this one, and it will probably be closed as "Won't Fix". But this is what happens when you compile with 2.0 and run with 1.x (or vice versa):

```
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:186)
	at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:133)
	... 6 more
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.SpringApplication.run(Ljava/lang/Class;[Ljava/lang/String;)Lorg/springframework/context/ConfigurableApplicationContext;
	at com.example.LauncherApplication.main(LauncherApplication.java:21)
	... 15 more
```

**Comment by dsyer** [comment]
How would that help?

**Comment by dsyer** [comment]
Here's an approach that works if anyone needs it: https://github.com/dsyer/spring-boot-legacy-agent
